# Actions
ACTION_CREATE = 'create'
ACTION_DELETE = 'delete'
ACTION_UPDATE = 'update'
ACTION_RUN = 'run'
ACTION_TEST = 'test'
ACTION_BUILD = 'build'
ACTION_DEPLOY = 'deploy'
ACTION_ANALYZE = 'analyze'
ACTION_FIX = 'fix'
ACTION_CONVERT = 'convert'

# Subjects
SUBJECT_PROJECT = 'project'
SUBJECT_FILE = 'file'
SUBJECT_DIRECTORY = 'directory'
SUBJECT_CONFIG = 'config'
SUBJECT_DEPENDENCIES = 'dependencies'
SUBJECT_SETTINGS = 'settings'
SUBJECT_SCRIPT = 'script'
SUBJECT_COMMAND = 'command'
SUBJECT_APP = 'app'
SUBJECT_SERVICE = 'service'
SUBJECT_CODE = 'code'
SUBJECT_LOGS = 'logs'
SUBJECT_DATA = 'data'
SUBJECT_DOCS = 'docs'
SUBJECT_REPORT = 'report'

# Types
TYPE_NODE = 'node'
TYPE_PYTHON = 'python'
TYPE_JAVA = 'java'
TYPE_HTML = 'html'
TYPE_CSS = 'css'
TYPE_JAVASCRIPT = 'javascript'
TYPE_TYPESCRIPT = 'typescript'
TYPE_DOTNET = 'dotnet'
TYPE_CSHARP = 'c#'
TYPE_JSON = 'json'
TYPE_YAML = 'yaml'
TYPE_NPM = 'npm'
TYPE_PIP = 'pip'
TYPE_DOCKER = 'docker'
TYPE_ENV = 'env'
TYPE_SHELL = 'shell'
TYPE_PYTEST = 'pytest'
TYPE_JEST = 'jest'
TYPE_MOCHA = 'mocha'
TYPE_WEBPACK = 'webpack'
TYPE_GRADLE = 'gradle'
TYPE_KUBERNETES = 'kubernetes'
TYPE_AWS = 'aws'
TYPE_LINT = 'lint'
TYPE_SECURITY = 'security'
TYPE_PERFORMANCE = 'performance'
TYPE_BUG = 'bug'
TYPE_SWAGGER = 'swagger'
TYPE_MARKDOWN = 'markdown'

# Argument flags
ARG_PROMPT = '-p'
ARG_VERSION = '-v'
ARG_NAME = '-n'
ARG_TAG = '-t'

NAMED_ARGS = {
    ARG_PROMPT: 'prompt',
    ARG_VERSION: 'version',
    ARG_NAME: 'name',
    ARG_TAG: 'tag'
}

# Mapping actions to allowed subjects
ALLOWED_SUBJECTS = {
    ACTION_CREATE: [SUBJECT_PROJECT, SUBJECT_FILE, SUBJECT_DIRECTORY, SUBJECT_CONFIG, SUBJECT_DOCS],
    ACTION_DELETE: [SUBJECT_PROJECT, SUBJECT_FILE, SUBJECT_DIRECTORY, SUBJECT_CONFIG],
    ACTION_UPDATE: [SUBJECT_DEPENDENCIES, SUBJECT_CONFIG, SUBJECT_SETTINGS, SUBJECT_DOCS],
    ACTION_RUN: [SUBJECT_SCRIPT, SUBJECT_COMMAND, SUBJECT_APP],
    ACTION_TEST: [SUBJECT_CODE],
    ACTION_BUILD: [SUBJECT_PROJECT, SUBJECT_CODE],
    ACTION_DEPLOY: [SUBJECT_APP, SUBJECT_SERVICE],
    ACTION_ANALYZE: [SUBJECT_CODE, SUBJECT_LOGS, SUBJECT_DATA],
    ACTION_FIX: [SUBJECT_CODE, SUBJECT_CONFIG],
    ACTION_CONVERT: [SUBJECT_CODE, SUBJECT_CONFIG, SUBJECT_FILE]
}

# Mapping subjects to allowed types
ALLOWED_TYPES = {
    SUBJECT_PROJECT: [TYPE_NODE, TYPE_PYTHON, TYPE_JAVA, TYPE_DOTNET],
    SUBJECT_FILE: [TYPE_HTML, TYPE_CSS, TYPE_JSON, TYPE_YAML],
    SUBJECT_DEPENDENCIES: [TYPE_NPM, TYPE_PIP],
    SUBJECT_SCRIPT: [TYPE_SHELL, TYPE_PYTHON, TYPE_NODE],
    SUBJECT_CODE: [TYPE_NODE, TYPE_CSS, TYPE_HTML, TYPE_JAVA, TYPE_PYTHON, TYPE_JAVASCRIPT, TYPE_DOTNET]
}

# Mapping actions to allowed arguments
ALLOWED_ARGS = {
    ACTION_CREATE: [ARG_VERSION, ARG_NAME, ARG_PROMPT],
    ACTION_DELETE: [],
    ACTION_UPDATE: [],
    ACTION_RUN: [ARG_PROMPT],
    ACTION_TEST: [],
    ACTION_BUILD: [ARG_TAG],
    ACTION_DEPLOY: [ARG_PROMPT],
    ACTION_ANALYZE: [ARG_PROMPT],
    ACTION_FIX: [ARG_PROMPT],
    ACTION_CONVERT: [ARG_PROMPT]
}
